run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  funlen:
    lines: 150
    statements: 80

  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/stretchr/testify/require
          - github.com/stretchr/testify/assert
          - github.com/stretchr/testify/mock
          - github.com/cheggaaa/pb/v3
          - github.com/mailru/easyjson
          - github.com/google/uuid
          - github.com/Masterminds/squirrel
          - github.com/jackc/pgx/v4/pgxpool
          - github.com/ilyakaznacheev/cleanenv
          - github.com/grpc-ecosystem/grpc-gateway/v2/runtime
          - github.com/milov52/hw12_13_14_15_calendar/internal/app
          - github.com/milov52/hw12_13_14_15_calendar/internal/config
          - github.com/milov52/hw12_13_14_15_calendar/internal/converter/server
          - github.com/milov52/hw12_13_14_15_calendar/internal/service/event
          - github.com/milov52/hw12_13_14_15_calendar/pkg/api/event/v1'
          - github.com/milov52/hw12_13_14_15_calendar/internal/api/event
          - github.com/milov52/hw12_13_14_15_calendar/internal/model
          - github.com/milov52/hw12_13_14_15_calendar/internal/repository
          - github.com/milov52/hw12_13_14_15_calendar/pkg/api/event/v1
          - github.com/rabbitmq/amqp091-go
          - github.com/milov52/hw12_13_14_15_calendar/internal/logger
          - github.com/milov52/hw12_13_14_15_calendar/internal/queue/rabbitmq
          - github.com/milov52/hw12_13_14_15_calendar/internal/service/sender
          - github.com/milov52/hw12_13_14_15_calendar/internal/service/scheduler
          - github.com/milov52/hw12_13_14_15_calendar/internal/service/calendar

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec
    - path: internal/config/config.go
      linters:
        - tagliatelle

linters:
  disable-all: true
  enable:
    - asciicheck
    - depguard
    - dogsled
    - dupl
    - bodyclose
    - durationcheck
    - errorlint
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace
