version: '3'

volumes:
  postgres_volume_local:
  postgres_volume_test:

services:
  pg-local:
    image: postgres:14-alpine3.17

    env_file:
      - "../local.env"
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data

  pg-test:
    image: postgres:14-alpine3.17

    env_file:
      - "../local.env"
    ports:
      - "54322:5432"
    volumes:
      - postgres_volume_test:/var/lib/postgresql/data
