env: "local" # local, dev, prod
default_storage: "sql"
database:
  host: "pg"
  port: 5432
  username: "postgres"
  password: "postgres"
  dbname: "calendar"

http_server:
  host: "0.0.0.0"
  port: "8080"
  timeout: 4s
  idle_timeout: 60s

grpc_server:
  host: "localhost"
  port: "50051"

rabbitmq:
  host: "rabbitmq"
  port: "5672"
  username: "guest"
  password: "guest"

scheduler:
  launch_frequency: 5s