env: "local" # local, dev, prod
default_storage: "sql"
database:
  host: "localhost"
  port: 54321
  username: "calendar-user"
  password: "calendar-password"
  dbname: "calendar"

http_server:
  host: "localhost"
  port: "8081"
  timeout: 4s
  idle_timeout: 60s

grpc_server:
  host: "localhost"
  port: "50051"

rabbitmq:
  host: "localhost"
  port: "5672"
  username: "guest"
  password: "guest"

scheduler:
  launch_frequency: 5s