env: "local" # local, dev, prod
database:
  host: "localhost"
  port: 54321
  username: "calendar-user"
  password: "calendar-password"
  dbname: "calendar"

http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s