apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rabbitmq
spec:
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
    - port: 15672
      targetPort: 15672
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-rabbitmq