version: '3.8'

networks:
  rabbit:
    driver: bridge
  db:
    driver: bridge

services:
  calendar_app:
    build: cmd/calendar
    depends_on:
      - migrator
    ports:
      - "8888:8080"
    expose:
      - 8888
    networks:
      - db

  sender:
    build: cmd/calendar_sender
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - db
      - rabbit

  scheduler:
    build: cmd/calendar_sheduler
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - db
      - rabbit

  migrator:
    build: migrations
    depends_on:
      - pg
    restart: on-failure
    networks:
      - db

  pg:
    restart: always
    image: postgres:latest
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "5435:5432"
    volumes:
      - ./internal/pg/data:/var/lib/postgresql/data
    networks:
      - db

  rabbitmq:
    image: rabbitmq:3.13.3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15675:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 15s
      timeout: 15s
      retries: 10
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - rabbit